name: Build & Deploy (Ignite → GitHub Pages)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Swift
        run: |
          sudo apt-get update && sudo apt-get install -y libcurl4-openssl-dev
          curl -O https://download.swift.org/swiftly/linux/swiftly-$(uname -m).tar.gz
          tar zxf swiftly-$(uname -m).tar.gz
          ./swiftly init --verbose --assume-yes --skip-install
          . ~/.local/share/swiftly/env.sh
          swiftly install 6.0
          echo "$(dirname $(which swift))" >> $GITHUB_PATH

      - run: swift --version

      - name: Build site with Ignite
        run: |
          swift build -c release
          ignite build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: Build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
